# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datanalyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('boughtat', models.IntegerField()),
                ('usern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
