# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datanalyse', '0007_usermoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
