# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datanalyse', '0002_userport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userport',
            old_name='usern',
            new_name='user',
        ),
    ]
