# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datanalyse', '0008_tickercomp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerComp',
        ),
    ]
